In [9]:
import numpy as np
import matplotlib.pyplot as plt

X_0 = np.array([[0],[0]])
delta_X = np.random.normal(0,1,(2,5))
X = np.concatenate((X_0, np.cumsum(delta_X, axis=1)),axis=1)
#plt.plot(X[0],X[1],"ro-")
#plt.savefig('test.pdf')

print(X)

[[ 0.         -0.27338164  0.95517242  2.59409756  2.84050855  4.26247774]
 [ 0.         -0.45634629 -0.02318636 -0.14976587  0.41190366  0.23425252]]


In [10]:
print(delta_X)

[[-0.27338164  1.22855406  1.63892515  0.24641099  1.42196919]
 [-0.45634629  0.43315993 -0.12657951  0.56166953 -0.17765115]]
